name: Check

on:
  pull_request:

defaults:
  run:
    shell: bash -xeuo pipefail {0}

concurrency:
  group: "check-${{ github.ref }}"
  cancel-in-progress: true

env:
  HOMEBREW_NO_AUTO_UPDATE: 1
  HOMEBREW_NO_ENV_HINTS: 1

permissions: {}

jobs:
  check:
    name: just check
    runs-on: macos-latest
    permissions:
      contents: read
    steps:
      - uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v6.0.2
        with:
          persist-credentials: false

      - name: Install tools
        run: brew install just swiftlint zizmor

      - uses: actions/setup-node@53b83947a5a98c8d113130e565377fae1a50d02f # v6.3.0
        with:
          node-version: 24

      - name: Install site dependencies
        working-directory: site
        run: npm ci

      - name: Run checks
        run: just check
